name: Deploy to Server

on:
  pull_request:
    branches:
      - prod
    types: 
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add the deploy key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
      shell: bash

    - name: Set permissions for the deploy key
      run: chmod 600 ~/.ssh/deploy_key

    - name: Add server to known_hosts
      run: ssh-keyscan pharmaconeg.com >> ~/.ssh/known_hosts

    - name: SCP files to server
      run: scp -i ~/.ssh/deploy_key -r .next pharmax3@pharmaconeg.com:public_html
